"""The seen two-agency world, generated by the pinned agency-data-commons (PR 10).

Agency A is the frozen snapshot (its clients.csv has the same SHA-256 as commons' seed 42
reference). Agency B and the truth files are generated by commons' own `generate-multi` into the
git-ignored fixtures/generated/multi-a-b/, then checked byte for byte against the hashes of the
files commons commits at tag v0.2.0. PR 10 measured it before any tuning, then PR 10b tuned the
matcher on it, so it is now a seen regression set, not held out.
"""

import hashlib
import shutil
import tempfile
from pathlib import Path

COMMONS_VERSION = "0.2.0"
TWO_AGENCY_LABEL = (
    f"seen: generated by agency-data-commons v{COMMONS_VERSION}; the matcher was tuned on it "
    "(PR 10b), so these are not results on unseen data"
)
SEED = 42  # agency A's seed; commons gives agency B seed 43
# SHA-256 of commons' committed fixtures/multi-a-b/ at v0.2.0 (a9a670f), for the files read here.
EXPECTED_SHA256 = {
    "agency-b/canonical/clients.csv": (
        "b63ee18ed039b6c558b0b817e75b9e1f923243099f03dad05171572021770bcb"
    ),
    "agency-b/canonical/households.csv": (
        "ec20bf514ccaa329cb612b8b2e9f644c206ed502b0a4f2c75a49ad8b0340d996"
    ),
    "agency-b/canonical/policies.csv": (
        "28c38632b92f5b70f6d941c10dfae014d193e6ddb854eab27b879dc9bd85823d"
    ),
    "agency-b/drop/enrollment_export.csv": (
        "a77be8e4a807c5f407870da191a82df04184620580a0dd2657794cd14ddf5d74"
    ),
    "agency-b/ground_truth.json": (
        "3776ea5ff0e392f1fc9d297843d09217a2365a90a381e1822c9444f1b9c0c727"
    ),
    "cluster_truth.json": "ef3589162f41e8a85713df3767904ca0072855cd95e2c7b84a4f256d33abb59b",
    "must_not_merge.jsonl": "b289547b041f13eaa224989ab8dbf987f15b9fe56bdb7b80d48b7911d8d75f5c",
    "pair_truth.jsonl": "7ec87ce7d5e17d3662c97f991039ee2a73b85a8c3a3a25a9d538ca1b4a8938df",
}


def _matches(folder: Path) -> list[str]:
    """Files that are missing or differ from the expected hash."""
    return [
        rel
        for rel, digest in EXPECTED_SHA256.items()
        if not (folder / rel).is_file()
        or hashlib.sha256((folder / rel).read_bytes()).hexdigest() != digest
    ]


def ensure_multi_a_b(fixtures: Path) -> Path:
    """Return fixtures/generated/multi-a-b, generating it first if it is missing or changed.
    Generation is deterministic (about 3 seconds) and written to a temp folder, then moved."""
    folder = fixtures / "generated" / "multi-a-b"
    if not _matches(folder):
        return folder
    from synth_agency_data.cli import generate_multi  # imported late: only this world needs it

    folder.parent.mkdir(parents=True, exist_ok=True)
    tmp = Path(tempfile.mkdtemp(prefix=".multi-a-b-", dir=folder.parent))
    try:
        generate_multi(out=tmp, seed=SEED, agency_a=False)
        if bad := _matches(tmp):
            raise RuntimeError(f"agency-data-commons generated different bytes for {bad}")
        if folder.exists():
            shutil.rmtree(folder)
        tmp.rename(folder)
    finally:
        if tmp.exists():
            shutil.rmtree(tmp)
    return folder
